name: Publish to NPM
on:
  push:
    ### Publish on new tag release
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install NPM Dependencies
        run: npm i --legacy-peer-deps
      - name: Build project
        run: npm run build
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v2
        with:
          strategy: all
          token: ${{ secrets.NPM_TOKEN }}
          package: dist/ng-store/package.json
          access: public
